project_name: lorawan-stack

changelog:
  skip: true

release:
  prerelease: auto

builds:
  - id: stack
    main: ./cmd/tti-lw-stack
    binary: tti-lw-stack
    flags:
    - -tags=tti
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

  - id: cli
    main: ./cmd/tti-lw-cli
    binary: tti-lw-cli
    flags:
    - -tags=tti
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - id: stack
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - cli
      - stack
    files:
      - LICENSE
      - README.md
      - public/**/*
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

  - id: cli
    name_template: "{{ .ProjectName }}-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - cli
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: stack
    builds:
      - cli
      - stack
    vendor: The Things Industries
    homepage: https://www.thethingsindustries.com
    maintainer: The Things Industries <stack@thethingsindustries.com>
    description: The Things Stack for LoRaWAN
    license: TTI EULA
    formats:
      - deb
      - rpm
    recommends:
      - redis
      - cockroach
    files:
      "public/**/*": "/srv/ttn-lorawan/public"

# TODO: Re-enable (https://github.com/TheThingsIndustries/lorawan-stack/issues/1700).
#snapcrafts:
#  - id: stack
#    builds:
#      - cli
#      - stack
#    name: ttn-lw-stack
#    summary: The Things Stack for LoRaWAN
#    description: The Things Stack for LoRaWAN
#    grade: stable
#    confinement: strict
#    publish: true
#    apps:
#      ttn-lw-stack:
#        plugs: [ home, network, network-bind ]
#      ttn-lw-cli:
#        plugs: [ home, network, network-bind ]

brews:
  - name: tti-lw-stack
    ids:
      - stack
    github:
      owner: TheThingsIndustries
      name: homebrew-lorawan-stack
    commit_author:
      name: tti-ci
      email: stack@thethingsindustries.com
    homepage: https://www.thethingsindustries.com
    description: The Things Stack for LoRaWAN
    conflicts:
      - tti-lw-cli
    skip_upload: auto
    install: |
      bin.install "tti-lw-cli"
      libexec.install %w[tti-lw-stack public]
      env = {
          :TTN_LW_HTTP_STATIC_SEARCH_PATH => libexec/"public"
      }
      (bin/"tti-lw-stack").write_env_script libexec/"tti-lw-stack", env

  - name: tti-lw-cli
    ids:
      - cli
    github:
      owner: TheThingsIndustries
      name: homebrew-lorawan-stack
    commit_author:
      name: tti-ci
      email: stack@thethingsindustries.com
    homepage: https://www.thethingsindustries.com
    description: CLI of The Things Stack for LoRaWAN
    conflicts:
      - tti-lw-stack
    skip_upload: auto
    install: |
      bin.install "tti-lw-cli"

blobs:
  - provider: s3
    # NOTE: GoReleaser documentation says that bucket is a template, but it's not.
    bucket: the-things-enterprise-stack-releases
    ids:
    - stack
    - cli
    folder: "{{ .Version }}"

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - tti-lw-cli
      - tti-lw-stack
    image_templates:
      - '{{ or (index .Env "DOCKER_IMAGE") "lorawan-stack" }}:{{ .Major }}.{{ .Minor }}'
      - '{{ or (index .Env "DOCKER_IMAGE") "lorawan-stack" }}:{{ .Version }}'
    skip_push: auto
    extra_files:
      - public
  - goos: linux
    goarch: amd64
    binaries:
      - ttn-lw-cli
      - ttn-lw-stack
    image_templates:
      - '{{ or (index .Env "DOCKER_IMAGE") "lorawan-stack" }}:latest'
    skip_push: true
    extra_files:
      - public
