// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package ttipb

var ApplicationAPIKeyFieldPathsNested = []string{
	"api_key",
	"application_ids",
}

var ApplicationAPIKeyFieldPathsTopLevel = []string{
	"api_key",
	"application_ids",
}
