// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package ttipb

var ConfigurationFieldPathsNested = []string{
	"default_cluster",
	"default_cluster.is",
	"default_cluster.is.user_registration",
	"default_cluster.is.user_registration.admin_approval",
	"default_cluster.is.user_registration.admin_approval.required",
	"default_cluster.is.user_registration.contact_info_validation",
	"default_cluster.is.user_registration.contact_info_validation.required",
	"default_cluster.is.user_registration.invitation",
	"default_cluster.is.user_registration.invitation.required",
	"default_cluster.is.user_registration.invitation.token_ttl",
	"default_cluster.is.user_registration.password_requirements",
	"default_cluster.is.user_registration.password_requirements.max_length",
	"default_cluster.is.user_registration.password_requirements.min_digits",
	"default_cluster.is.user_registration.password_requirements.min_length",
	"default_cluster.is.user_registration.password_requirements.min_special",
	"default_cluster.is.user_registration.password_requirements.min_uppercase",
	"default_cluster.ns",
	"default_cluster.ns.cooldown_window",
	"default_cluster.ns.deduplication_window",
	"default_cluster.ns.dev_addr_prefixes",
	"default_cluster.ui",
	"default_cluster.ui.branding_base_url",
}

var ConfigurationFieldPathsTopLevel = []string{
	"default_cluster",
}
var Configuration_UIFieldPathsNested = []string{
	"branding_base_url",
}

var Configuration_UIFieldPathsTopLevel = []string{
	"branding_base_url",
}
var Configuration_ClusterFieldPathsNested = []string{
	"is",
	"is.user_registration",
	"is.user_registration.admin_approval",
	"is.user_registration.admin_approval.required",
	"is.user_registration.contact_info_validation",
	"is.user_registration.contact_info_validation.required",
	"is.user_registration.invitation",
	"is.user_registration.invitation.required",
	"is.user_registration.invitation.token_ttl",
	"is.user_registration.password_requirements",
	"is.user_registration.password_requirements.max_length",
	"is.user_registration.password_requirements.min_digits",
	"is.user_registration.password_requirements.min_length",
	"is.user_registration.password_requirements.min_special",
	"is.user_registration.password_requirements.min_uppercase",
	"ns",
	"ns.cooldown_window",
	"ns.deduplication_window",
	"ns.dev_addr_prefixes",
	"ui",
	"ui.branding_base_url",
}

var Configuration_ClusterFieldPathsTopLevel = []string{
	"is",
	"ns",
	"ui",
}
var Configuration_Cluster_IdentityServerFieldPathsNested = []string{
	"user_registration",
	"user_registration.admin_approval",
	"user_registration.admin_approval.required",
	"user_registration.contact_info_validation",
	"user_registration.contact_info_validation.required",
	"user_registration.invitation",
	"user_registration.invitation.required",
	"user_registration.invitation.token_ttl",
	"user_registration.password_requirements",
	"user_registration.password_requirements.max_length",
	"user_registration.password_requirements.min_digits",
	"user_registration.password_requirements.min_length",
	"user_registration.password_requirements.min_special",
	"user_registration.password_requirements.min_uppercase",
}

var Configuration_Cluster_IdentityServerFieldPathsTopLevel = []string{
	"user_registration",
}
var Configuration_Cluster_NetworkServerFieldPathsNested = []string{
	"cooldown_window",
	"deduplication_window",
	"dev_addr_prefixes",
}

var Configuration_Cluster_NetworkServerFieldPathsTopLevel = []string{
	"cooldown_window",
	"deduplication_window",
	"dev_addr_prefixes",
}
var Configuration_Cluster_IdentityServer_UserRegistrationFieldPathsNested = []string{
	"admin_approval",
	"admin_approval.required",
	"contact_info_validation",
	"contact_info_validation.required",
	"invitation",
	"invitation.required",
	"invitation.token_ttl",
	"password_requirements",
	"password_requirements.max_length",
	"password_requirements.min_digits",
	"password_requirements.min_length",
	"password_requirements.min_special",
	"password_requirements.min_uppercase",
}

var Configuration_Cluster_IdentityServer_UserRegistrationFieldPathsTopLevel = []string{
	"admin_approval",
	"contact_info_validation",
	"invitation",
	"password_requirements",
}
var Configuration_Cluster_IdentityServer_UserRegistration_InvitationFieldPathsNested = []string{
	"required",
	"token_ttl",
}

var Configuration_Cluster_IdentityServer_UserRegistration_InvitationFieldPathsTopLevel = []string{
	"required",
	"token_ttl",
}
var Configuration_Cluster_IdentityServer_UserRegistration_ContactInfoValidationFieldPathsNested = []string{
	"required",
}

var Configuration_Cluster_IdentityServer_UserRegistration_ContactInfoValidationFieldPathsTopLevel = []string{
	"required",
}
var Configuration_Cluster_IdentityServer_UserRegistration_AdminApprovalFieldPathsNested = []string{
	"required",
}

var Configuration_Cluster_IdentityServer_UserRegistration_AdminApprovalFieldPathsTopLevel = []string{
	"required",
}
var Configuration_Cluster_IdentityServer_UserRegistration_PasswordRequirementsFieldPathsNested = []string{
	"max_length",
	"min_digits",
	"min_length",
	"min_special",
	"min_uppercase",
}

var Configuration_Cluster_IdentityServer_UserRegistration_PasswordRequirementsFieldPathsTopLevel = []string{
	"max_length",
	"min_digits",
	"min_length",
	"min_special",
	"min_uppercase",
}
