// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package ttipb

var ExternalUserFieldPathsNested = []string{
	"created_at",
	"external_id",
	"provider",
	"updated_at",
	"user_ids",
}

var ExternalUserFieldPathsTopLevel = []string{
	"created_at",
	"external_id",
	"provider",
	"updated_at",
	"user_ids",
}
