// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package ttipb

var LicenseFieldPathsNested = []string{
	"address_regexps",
	"components",
	"created_at",
	"dev_addr_prefixes",
	"id",
	"id.license_id",
	"join_eui_prefixes",
	"license_issuer_ids",
	"license_issuer_ids.license_issuer_id",
	"limit_for",
	"max_applications",
	"max_clients",
	"max_end_devices",
	"max_gateways",
	"max_organizations",
	"max_users",
	"multi_tenancy",
	"valid_from",
	"valid_until",
	"warn_for",
}

var LicenseFieldPathsTopLevel = []string{
	"address_regexps",
	"components",
	"created_at",
	"dev_addr_prefixes",
	"id",
	"join_eui_prefixes",
	"license_issuer_ids",
	"limit_for",
	"max_applications",
	"max_clients",
	"max_end_devices",
	"max_gateways",
	"max_organizations",
	"max_users",
	"multi_tenancy",
	"valid_from",
	"valid_until",
	"warn_for",
}
var LicenseKeyFieldPathsNested = []string{
	"license",
	"signatures",
}

var LicenseKeyFieldPathsTopLevel = []string{
	"license",
	"signatures",
}
var LicenseKey_SignatureFieldPathsNested = []string{
	"key_id",
	"signature",
}

var LicenseKey_SignatureFieldPathsTopLevel = []string{
	"key_id",
	"signature",
}
