// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package ttipb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/gogo/protobuf/types"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = types.DynamicAny{}
)

// define the regex for a UUID once up-front
var _license_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// ValidateFields checks the field values on License with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *License) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = LicenseFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "id":

			if v, ok := interface{}(&m.LicenseIdentifiers).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return LicenseValidationError{
						field:  "id",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		case "license_issuer_ids":

			if v, ok := interface{}(&m.LicenseIssuerIdentifiers).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return LicenseValidationError{
						field:  "license_issuer_ids",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		case "created_at":

			if v, ok := interface{}(&m.CreatedAt).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return LicenseValidationError{
						field:  "created_at",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		case "valid_from":

			if v, ok := interface{}(&m.ValidFrom).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return LicenseValidationError{
						field:  "valid_from",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		case "valid_until":

			if v, ok := interface{}(&m.ValidUntil).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return LicenseValidationError{
						field:  "valid_until",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		case "components":

		case "address_regexps":

		case "dev_addr_prefixes":

		case "join_eui_prefixes":

		default:
			return LicenseValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// LicenseValidationError is the validation error returned by
// License.ValidateFields if the designated constraints aren't met.
type LicenseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LicenseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LicenseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LicenseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LicenseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LicenseValidationError) ErrorName() string { return "LicenseValidationError" }

// Error satisfies the builtin error interface
func (e LicenseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLicense.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LicenseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LicenseValidationError{}

// ValidateFields checks the field values on LicenseKey with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *LicenseKey) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = LicenseKeyFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "license":
			// no validation rules for License
		case "signatures":

			for idx, item := range m.GetSignatures() {
				_, _ = idx, item

				if v, ok := interface{}(item).(interface{ ValidateFields(...string) error }); ok {
					if err := v.ValidateFields(subs...); err != nil {
						return LicenseKeyValidationError{
							field:  fmt.Sprintf("signatures[%v]", idx),
							reason: "embedded message failed validation",
							cause:  err,
						}
					}
				}

			}

		default:
			return LicenseKeyValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// LicenseKeyValidationError is the validation error returned by
// LicenseKey.ValidateFields if the designated constraints aren't met.
type LicenseKeyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LicenseKeyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LicenseKeyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LicenseKeyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LicenseKeyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LicenseKeyValidationError) ErrorName() string { return "LicenseKeyValidationError" }

// Error satisfies the builtin error interface
func (e LicenseKeyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLicenseKey.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LicenseKeyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LicenseKeyValidationError{}

// ValidateFields checks the field values on LicenseKey_Signature with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *LicenseKey_Signature) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = LicenseKey_SignatureFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "key_id":
			// no validation rules for KeyID
		case "signature":
			// no validation rules for Signature
		default:
			return LicenseKey_SignatureValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// LicenseKey_SignatureValidationError is the validation error returned by
// LicenseKey_Signature.ValidateFields if the designated constraints aren't met.
type LicenseKey_SignatureValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LicenseKey_SignatureValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LicenseKey_SignatureValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LicenseKey_SignatureValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LicenseKey_SignatureValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LicenseKey_SignatureValidationError) ErrorName() string {
	return "LicenseKey_SignatureValidationError"
}

// Error satisfies the builtin error interface
func (e LicenseKey_SignatureValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLicenseKey_Signature.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LicenseKey_SignatureValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LicenseKey_SignatureValidationError{}
