// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorawan-stack/api/tti/tenant.proto

package ttipb

import (
	fmt "fmt"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"
	time "time"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	ttnpb "go.thethings.network/lorawan-stack/pkg/ttnpb"
	go_thethings_network_lorawan_stack_pkg_types "go.thethings.network/lorawan-stack/pkg/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Tenant is the message that defines a Tenant in the network.
type Tenant struct {
	TenantIdentifiers `protobuf:"bytes,1,opt,name=ids,proto3,embedded=ids" json:"ids"`
	CreatedAt         time.Time            `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	UpdatedAt         time.Time            `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at"`
	Name              string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description       string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Attributes        map[string]string    `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ContactInfo       []*ttnpb.ContactInfo `protobuf:"bytes,7,rep,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	// The reviewing state of the tenant.
	// This field can only be modified by tenant admins.
	State                ttnpb.State  `protobuf:"varint,8,opt,name=state,proto3,enum=ttn.lorawan.v3.State" json:"state,omitempty"`
	Capabilities         types.Struct `protobuf:"bytes,9,opt,name=capabilities,proto3" json:"capabilities"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Tenant) Reset()      { *m = Tenant{} }
func (*Tenant) ProtoMessage() {}
func (*Tenant) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2ae00655d4b280, []int{0}
}
func (m *Tenant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tenant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tenant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tenant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tenant.Merge(m, src)
}
func (m *Tenant) XXX_Size() int {
	return m.Size()
}
func (m *Tenant) XXX_DiscardUnknown() {
	xxx_messageInfo_Tenant.DiscardUnknown(m)
}

var xxx_messageInfo_Tenant proto.InternalMessageInfo

func (m *Tenant) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *Tenant) GetUpdatedAt() time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return time.Time{}
}

func (m *Tenant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tenant) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Tenant) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Tenant) GetContactInfo() []*ttnpb.ContactInfo {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *Tenant) GetState() ttnpb.State {
	if m != nil {
		return m.State
	}
	return ttnpb.STATE_REQUESTED
}

func (m *Tenant) GetCapabilities() types.Struct {
	if m != nil {
		return m.Capabilities
	}
	return types.Struct{}
}

type Tenants struct {
	Tenants              []*Tenant `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Tenants) Reset()      { *m = Tenants{} }
func (*Tenants) ProtoMessage() {}
func (*Tenants) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2ae00655d4b280, []int{1}
}
func (m *Tenants) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tenants) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tenants.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tenants) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tenants.Merge(m, src)
}
func (m *Tenants) XXX_Size() int {
	return m.Size()
}
func (m *Tenants) XXX_DiscardUnknown() {
	xxx_messageInfo_Tenants.DiscardUnknown(m)
}

var xxx_messageInfo_Tenants proto.InternalMessageInfo

func (m *Tenants) GetTenants() []*Tenant {
	if m != nil {
		return m.Tenants
	}
	return nil
}

type GetTenantRequest struct {
	TenantIdentifiers    `protobuf:"bytes,1,opt,name=tenant_ids,json=tenantIds,proto3,embedded=tenant_ids" json:"tenant_ids"`
	FieldMask            types.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTenantRequest) Reset()      { *m = GetTenantRequest{} }
func (*GetTenantRequest) ProtoMessage() {}
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2ae00655d4b280, []int{2}
}
func (m *GetTenantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetTenantRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantRequest.Merge(m, src)
}
func (m *GetTenantRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantRequest proto.InternalMessageInfo

func (m *GetTenantRequest) GetFieldMask() types.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return types.FieldMask{}
}

type ListTenantsRequest struct {
	FieldMask types.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask"`
	// Order the results by this field path (must be present in the field mask).
	// Default ordering is by ID. Prepend with a minus (-) to reverse the order.
	Order string `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	// Limit the number of results per page.
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Page number for pagination. 0 is interpreted as 1.
	Page                 uint32   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTenantsRequest) Reset()      { *m = ListTenantsRequest{} }
func (*ListTenantsRequest) ProtoMessage() {}
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2ae00655d4b280, []int{3}
}
func (m *ListTenantsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListTenantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListTenantsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListTenantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTenantsRequest.Merge(m, src)
}
func (m *ListTenantsRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListTenantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTenantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTenantsRequest proto.InternalMessageInfo

func (m *ListTenantsRequest) GetFieldMask() types.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return types.FieldMask{}
}

func (m *ListTenantsRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *ListTenantsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListTenantsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CreateTenantRequest struct {
	Tenant               `protobuf:"bytes,1,opt,name=tenant,proto3,embedded=tenant" json:"tenant"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTenantRequest) Reset()      { *m = CreateTenantRequest{} }
func (*CreateTenantRequest) ProtoMessage() {}
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2ae00655d4b280, []int{4}
}
func (m *CreateTenantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateTenantRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTenantRequest.Merge(m, src)
}
func (m *CreateTenantRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTenantRequest proto.InternalMessageInfo

type UpdateTenantRequest struct {
	Tenant               `protobuf:"bytes,1,opt,name=tenant,proto3,embedded=tenant" json:"tenant"`
	FieldMask            types.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateTenantRequest) Reset()      { *m = UpdateTenantRequest{} }
func (*UpdateTenantRequest) ProtoMessage() {}
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2ae00655d4b280, []int{5}
}
func (m *UpdateTenantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateTenantRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTenantRequest.Merge(m, src)
}
func (m *UpdateTenantRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdateTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTenantRequest proto.InternalMessageInfo

func (m *UpdateTenantRequest) GetFieldMask() types.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return types.FieldMask{}
}

type GetTenantIdentifiersForEndDeviceEUIsRequest struct {
	JoinEUI              go_thethings_network_lorawan_stack_pkg_types.EUI64 `protobuf:"bytes,1,opt,name=join_eui,json=joinEui,proto3,customtype=go.thethings.network/lorawan-stack/pkg/types.EUI64" json:"join_eui"`
	DevEUI               go_thethings_network_lorawan_stack_pkg_types.EUI64 `protobuf:"bytes,2,opt,name=dev_eui,json=devEui,proto3,customtype=go.thethings.network/lorawan-stack/pkg/types.EUI64" json:"dev_eui"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *GetTenantIdentifiersForEndDeviceEUIsRequest) Reset() {
	*m = GetTenantIdentifiersForEndDeviceEUIsRequest{}
}
func (*GetTenantIdentifiersForEndDeviceEUIsRequest) ProtoMessage() {}
func (*GetTenantIdentifiersForEndDeviceEUIsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2ae00655d4b280, []int{6}
}
func (m *GetTenantIdentifiersForEndDeviceEUIsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTenantIdentifiersForEndDeviceEUIsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetTenantIdentifiersForEndDeviceEUIsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetTenantIdentifiersForEndDeviceEUIsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantIdentifiersForEndDeviceEUIsRequest.Merge(m, src)
}
func (m *GetTenantIdentifiersForEndDeviceEUIsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetTenantIdentifiersForEndDeviceEUIsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantIdentifiersForEndDeviceEUIsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantIdentifiersForEndDeviceEUIsRequest proto.InternalMessageInfo

type GetTenantIdentifiersForGatewayEUIRequest struct {
	EUI                  go_thethings_network_lorawan_stack_pkg_types.EUI64 `protobuf:"bytes,1,opt,name=eui,proto3,customtype=go.thethings.network/lorawan-stack/pkg/types.EUI64" json:"eui"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *GetTenantIdentifiersForGatewayEUIRequest) Reset() {
	*m = GetTenantIdentifiersForGatewayEUIRequest{}
}
func (*GetTenantIdentifiersForGatewayEUIRequest) ProtoMessage() {}
func (*GetTenantIdentifiersForGatewayEUIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2ae00655d4b280, []int{7}
}
func (m *GetTenantIdentifiersForGatewayEUIRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTenantIdentifiersForGatewayEUIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetTenantIdentifiersForGatewayEUIRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetTenantIdentifiersForGatewayEUIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantIdentifiersForGatewayEUIRequest.Merge(m, src)
}
func (m *GetTenantIdentifiersForGatewayEUIRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetTenantIdentifiersForGatewayEUIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantIdentifiersForGatewayEUIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantIdentifiersForGatewayEUIRequest proto.InternalMessageInfo

type GetTenantRegistryTotalsRequest struct {
	TenantIdentifiers    `protobuf:"bytes,1,opt,name=tenant_ids,json=tenantIds,proto3,embedded=tenant_ids" json:"tenant_ids"`
	FieldMask            types.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTenantRegistryTotalsRequest) Reset()      { *m = GetTenantRegistryTotalsRequest{} }
func (*GetTenantRegistryTotalsRequest) ProtoMessage() {}
func (*GetTenantRegistryTotalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2ae00655d4b280, []int{8}
}
func (m *GetTenantRegistryTotalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTenantRegistryTotalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetTenantRegistryTotalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetTenantRegistryTotalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantRegistryTotalsRequest.Merge(m, src)
}
func (m *GetTenantRegistryTotalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetTenantRegistryTotalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantRegistryTotalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantRegistryTotalsRequest proto.InternalMessageInfo

func (m *GetTenantRegistryTotalsRequest) GetFieldMask() types.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return types.FieldMask{}
}

type TenantRegistryTotals struct {
	Applications         uint64   `protobuf:"varint,1,opt,name=applications,proto3" json:"applications,omitempty"`
	Clients              uint64   `protobuf:"varint,2,opt,name=clients,proto3" json:"clients,omitempty"`
	EndDevices           uint64   `protobuf:"varint,3,opt,name=end_devices,json=endDevices,proto3" json:"end_devices,omitempty"`
	Gateways             uint64   `protobuf:"varint,4,opt,name=gateways,proto3" json:"gateways,omitempty"`
	Organizations        uint64   `protobuf:"varint,5,opt,name=organizations,proto3" json:"organizations,omitempty"`
	Users                uint64   `protobuf:"varint,6,opt,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantRegistryTotals) Reset()      { *m = TenantRegistryTotals{} }
func (*TenantRegistryTotals) ProtoMessage() {}
func (*TenantRegistryTotals) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2ae00655d4b280, []int{9}
}
func (m *TenantRegistryTotals) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TenantRegistryTotals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TenantRegistryTotals.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TenantRegistryTotals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantRegistryTotals.Merge(m, src)
}
func (m *TenantRegistryTotals) XXX_Size() int {
	return m.Size()
}
func (m *TenantRegistryTotals) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantRegistryTotals.DiscardUnknown(m)
}

var xxx_messageInfo_TenantRegistryTotals proto.InternalMessageInfo

func (m *TenantRegistryTotals) GetApplications() uint64 {
	if m != nil {
		return m.Applications
	}
	return 0
}

func (m *TenantRegistryTotals) GetClients() uint64 {
	if m != nil {
		return m.Clients
	}
	return 0
}

func (m *TenantRegistryTotals) GetEndDevices() uint64 {
	if m != nil {
		return m.EndDevices
	}
	return 0
}

func (m *TenantRegistryTotals) GetGateways() uint64 {
	if m != nil {
		return m.Gateways
	}
	return 0
}

func (m *TenantRegistryTotals) GetOrganizations() uint64 {
	if m != nil {
		return m.Organizations
	}
	return 0
}

func (m *TenantRegistryTotals) GetUsers() uint64 {
	if m != nil {
		return m.Users
	}
	return 0
}

func init() {
	proto.RegisterType((*Tenant)(nil), "tti.lorawan.v3.Tenant")
	golang_proto.RegisterType((*Tenant)(nil), "tti.lorawan.v3.Tenant")
	proto.RegisterMapType((map[string]string)(nil), "tti.lorawan.v3.Tenant.AttributesEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "tti.lorawan.v3.Tenant.AttributesEntry")
	proto.RegisterType((*Tenants)(nil), "tti.lorawan.v3.Tenants")
	golang_proto.RegisterType((*Tenants)(nil), "tti.lorawan.v3.Tenants")
	proto.RegisterType((*GetTenantRequest)(nil), "tti.lorawan.v3.GetTenantRequest")
	golang_proto.RegisterType((*GetTenantRequest)(nil), "tti.lorawan.v3.GetTenantRequest")
	proto.RegisterType((*ListTenantsRequest)(nil), "tti.lorawan.v3.ListTenantsRequest")
	golang_proto.RegisterType((*ListTenantsRequest)(nil), "tti.lorawan.v3.ListTenantsRequest")
	proto.RegisterType((*CreateTenantRequest)(nil), "tti.lorawan.v3.CreateTenantRequest")
	golang_proto.RegisterType((*CreateTenantRequest)(nil), "tti.lorawan.v3.CreateTenantRequest")
	proto.RegisterType((*UpdateTenantRequest)(nil), "tti.lorawan.v3.UpdateTenantRequest")
	golang_proto.RegisterType((*UpdateTenantRequest)(nil), "tti.lorawan.v3.UpdateTenantRequest")
	proto.RegisterType((*GetTenantIdentifiersForEndDeviceEUIsRequest)(nil), "tti.lorawan.v3.GetTenantIdentifiersForEndDeviceEUIsRequest")
	golang_proto.RegisterType((*GetTenantIdentifiersForEndDeviceEUIsRequest)(nil), "tti.lorawan.v3.GetTenantIdentifiersForEndDeviceEUIsRequest")
	proto.RegisterType((*GetTenantIdentifiersForGatewayEUIRequest)(nil), "tti.lorawan.v3.GetTenantIdentifiersForGatewayEUIRequest")
	golang_proto.RegisterType((*GetTenantIdentifiersForGatewayEUIRequest)(nil), "tti.lorawan.v3.GetTenantIdentifiersForGatewayEUIRequest")
	proto.RegisterType((*GetTenantRegistryTotalsRequest)(nil), "tti.lorawan.v3.GetTenantRegistryTotalsRequest")
	golang_proto.RegisterType((*GetTenantRegistryTotalsRequest)(nil), "tti.lorawan.v3.GetTenantRegistryTotalsRequest")
	proto.RegisterType((*TenantRegistryTotals)(nil), "tti.lorawan.v3.TenantRegistryTotals")
	golang_proto.RegisterType((*TenantRegistryTotals)(nil), "tti.lorawan.v3.TenantRegistryTotals")
}

func init() { proto.RegisterFile("lorawan-stack/api/tti/tenant.proto", fileDescriptor_0b2ae00655d4b280) }
func init() {
	golang_proto.RegisterFile("lorawan-stack/api/tti/tenant.proto", fileDescriptor_0b2ae00655d4b280)
}

var fileDescriptor_0b2ae00655d4b280 = []byte{
	// 1130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x3f, 0x8c, 0x1b, 0xc5,
	0x17, 0xde, 0xf1, 0xdf, 0xf3, 0xdc, 0x25, 0x39, 0x4d, 0xf2, 0xfb, 0xb1, 0x72, 0x60, 0x7c, 0xac,
	0x4e, 0xc1, 0x09, 0xf1, 0x3a, 0x72, 0x00, 0x41, 0x10, 0x04, 0x3b, 0x71, 0xa2, 0x43, 0xd0, 0x6c,
	0x72, 0x42, 0x22, 0x0a, 0x66, 0xbc, 0x3b, 0xde, 0x0c, 0xb6, 0x77, 0x97, 0x9d, 0x59, 0x07, 0x07,
	0x21, 0x22, 0xaa, 0x88, 0x2a, 0x74, 0x11, 0x0d, 0x88, 0x86, 0x94, 0x69, 0x90, 0x52, 0xa6, 0x4c,
	0x83, 0x74, 0x65, 0x44, 0x71, 0xc4, 0xeb, 0xe6, 0x2a, 0x94, 0x32, 0xba, 0x0a, 0xed, 0xec, 0xfa,
	0xce, 0xbe, 0x3f, 0x12, 0xd1, 0x51, 0xd0, 0xcd, 0x9b, 0xf9, 0xde, 0xf7, 0xde, 0xfb, 0xde, 0x7b,
	0xbb, 0x50, 0xeb, 0xb9, 0x3e, 0xb9, 0x49, 0x9c, 0x0a, 0x17, 0xc4, 0xec, 0x56, 0x89, 0xc7, 0xaa,
	0x42, 0xb0, 0xaa, 0xa0, 0x0e, 0x71, 0x84, 0xee, 0xf9, 0xae, 0x70, 0xd1, 0x61, 0x21, 0x98, 0x9e,
	0xe0, 0xf4, 0xc1, 0xd9, 0x62, 0xdd, 0x66, 0xe2, 0x46, 0xd0, 0xd6, 0x4d, 0xb7, 0x5f, 0xa5, 0xce,
	0xc0, 0x1d, 0x7a, 0xbe, 0xfb, 0xd5, 0xb0, 0x2a, 0xc1, 0x66, 0xc5, 0xa6, 0x4e, 0x65, 0x40, 0x7a,
	0xcc, 0x22, 0x82, 0x56, 0x77, 0x1d, 0x62, 0xca, 0x62, 0x65, 0x8a, 0xc2, 0x76, 0x6d, 0x37, 0x76,
	0x6e, 0x07, 0x1d, 0x69, 0x49, 0x43, 0x9e, 0x12, 0xf8, 0x92, 0xed, 0xba, 0x76, 0x8f, 0x6e, 0xa3,
	0x3a, 0x8c, 0xf6, 0xac, 0x56, 0x9f, 0xf0, 0x6e, 0x82, 0x78, 0x79, 0x27, 0x82, 0x0b, 0x3f, 0x30,
	0x93, 0x0a, 0x8a, 0xa5, 0x9d, 0xaf, 0x82, 0xf5, 0x29, 0x17, 0xa4, 0xef, 0x25, 0x80, 0xe5, 0xdd,
	0x32, 0x98, 0xae, 0x23, 0x88, 0x29, 0x5a, 0xcc, 0xe9, 0x4c, 0xd2, 0x78, 0x65, 0x37, 0x8a, 0x3a,
	0x41, 0x9f, 0x27, 0xcf, 0xaf, 0xed, 0xad, 0x25, 0xb3, 0xa8, 0x23, 0x58, 0x87, 0x51, 0x3f, 0x01,
	0x6a, 0x3f, 0x64, 0x61, 0xee, 0xaa, 0x54, 0x18, 0x35, 0x61, 0x9a, 0x59, 0x5c, 0x05, 0x4b, 0xa0,
	0x3c, 0x5f, 0x7b, 0x55, 0x9f, 0x55, 0x5a, 0x8f, 0x41, 0x2b, 0xdb, 0x04, 0x8d, 0xc5, 0xcd, 0x46,
	0xf6, 0x7b, 0x90, 0x5a, 0x04, 0x8f, 0xd7, 0x4b, 0xca, 0xda, 0x7a, 0x09, 0x18, 0x91, 0x3f, 0xba,
	0x00, 0xa1, 0xe9, 0x53, 0x22, 0xa8, 0xd5, 0x22, 0x42, 0x4d, 0x49, 0xb6, 0xa2, 0x1e, 0x57, 0xad,
	0x4f, 0xaa, 0xd6, 0xaf, 0x4e, 0xaa, 0x6e, 0xcc, 0x45, 0xee, 0x77, 0xff, 0x2c, 0x01, 0xa3, 0x90,
	0xf8, 0xd5, 0x45, 0x44, 0x12, 0x78, 0xd6, 0x84, 0x24, 0xfd, 0x22, 0x24, 0x89, 0x5f, 0x5d, 0xa0,
	0xe3, 0x30, 0xe3, 0x90, 0x3e, 0x55, 0x33, 0x4b, 0xa0, 0x5c, 0x68, 0xe4, 0x37, 0x1b, 0x19, 0x3f,
	0xa5, 0xd6, 0x0c, 0x79, 0x89, 0x4e, 0xc1, 0x79, 0x8b, 0x72, 0xd3, 0x67, 0x9e, 0x60, 0xae, 0xa3,
	0x66, 0x25, 0x66, 0x6e, 0xb3, 0x91, 0xf5, 0xd3, 0xea, 0xda, 0x11, 0x63, 0xfa, 0x11, 0x09, 0x08,
	0x89, 0x10, 0x3e, 0x6b, 0x07, 0x82, 0x72, 0x35, 0xb7, 0x94, 0x2e, 0xcf, 0xd7, 0x4e, 0xec, 0x2d,
	0x90, 0x5e, 0xdf, 0x02, 0x36, 0x1d, 0xe1, 0x0f, 0x1b, 0xa7, 0x37, 0x1b, 0x27, 0x7f, 0x04, 0x27,
	0xb4, 0x65, 0x5f, 0x53, 0x97, 0x6b, 0xf8, 0xb3, 0x6b, 0xa4, 0x72, 0xeb, 0x4c, 0xe5, 0x9d, 0xeb,
	0xe5, 0xf3, 0xe7, 0xae, 0x55, 0xae, 0x9f, 0x9f, 0x98, 0x27, 0xbf, 0xae, 0x9d, 0xfe, 0x66, 0xd9,
	0x98, 0x8a, 0x83, 0xde, 0x87, 0x0b, 0xd3, 0x8d, 0x57, 0xf3, 0x32, 0xee, 0x71, 0x5d, 0x08, 0x67,
	0x3a, 0xee, 0x85, 0x18, 0xb3, 0xe2, 0x74, 0x5c, 0x63, 0xde, 0xdc, 0x36, 0xd0, 0x9b, 0x30, 0xcb,
	0x05, 0x11, 0x54, 0x9d, 0x5b, 0x02, 0xe5, 0xc3, 0xb5, 0xff, 0xed, 0x74, 0xbc, 0x12, 0x3d, 0xca,
	0x92, 0xbf, 0x8b, 0xba, 0x68, 0xc4, 0x68, 0x54, 0x87, 0x0b, 0x26, 0xf1, 0x48, 0x9b, 0xf5, 0x98,
	0x60, 0x94, 0xab, 0x05, 0x29, 0xfe, 0x4b, 0xbb, 0xc4, 0xbf, 0x22, 0xa7, 0xba, 0x91, 0x89, 0x94,
	0x37, 0x66, 0x5c, 0x8a, 0xef, 0xc1, 0x23, 0x3b, 0x64, 0x40, 0x8b, 0x30, 0xdd, 0xa5, 0x43, 0x39,
	0x5c, 0x05, 0x23, 0x3a, 0xa2, 0x63, 0x30, 0x3b, 0x20, 0xbd, 0x80, 0xca, 0x11, 0x29, 0x18, 0xb1,
	0x71, 0x2e, 0xf5, 0x36, 0xd0, 0xde, 0x85, 0xf9, 0x58, 0x4c, 0x8e, 0xce, 0xc0, 0x7c, 0xbc, 0xff,
	0xd1, 0x5c, 0x46, 0xe5, 0xff, 0x7f, 0x6f, 0xd9, 0x8d, 0x09, 0x4c, 0xfb, 0x15, 0xc0, 0xc5, 0xcb,
	0x54, 0x24, 0xd7, 0xf4, 0xcb, 0x80, 0x72, 0x81, 0x0c, 0x08, 0xe3, 0xf7, 0xd6, 0x01, 0x27, 0xbc,
	0x20, 0x12, 0x10, 0x47, 0xe7, 0x21, 0xdc, 0x5e, 0xfd, 0x7d, 0xe7, 0xfc, 0x52, 0x04, 0xf9, 0x98,
	0xf0, 0x6e, 0x22, 0x54, 0xa1, 0x33, 0xb9, 0xd0, 0x7e, 0x02, 0x10, 0x7d, 0xc4, 0x78, 0x92, 0x2a,
	0x9f, 0xe4, 0x3a, 0xcb, 0x0b, 0x5e, 0x98, 0x37, 0x12, 0xd6, 0xf5, 0x2d, 0xea, 0x4f, 0x84, 0x95,
	0x06, 0xc2, 0x30, 0xdb, 0x63, 0x7d, 0x16, 0x2f, 0xd3, 0x21, 0xd9, 0xf6, 0x53, 0x69, 0x75, 0x23,
	0x6f, 0xc4, 0xd7, 0x08, 0xc1, 0x8c, 0x47, 0xec, 0x78, 0x59, 0x0e, 0x19, 0xf2, 0xac, 0x7d, 0x02,
	0x8f, 0x5e, 0x90, 0x2b, 0x39, 0xab, 0xe6, 0x07, 0x30, 0x17, 0xcb, 0x90, 0x64, 0xb7, 0x4f, 0x4f,
	0xf6, 0x90, 0x2f, 0xf1, 0xd3, 0xee, 0x01, 0x78, 0x74, 0x55, 0xee, 0xe9, 0xbf, 0xcc, 0x7c, 0xf0,
	0xae, 0xfc, 0x05, 0xe0, 0xeb, 0x5b, 0xf3, 0x33, 0x35, 0x0c, 0x97, 0x5c, 0xbf, 0xe9, 0x58, 0x17,
	0xe9, 0x80, 0x99, 0xb4, 0xb9, 0xba, 0xb2, 0xd5, 0xae, 0xcf, 0xe1, 0xdc, 0x17, 0x2e, 0x73, 0x5a,
	0x34, 0x60, 0x32, 0xe9, 0x85, 0x46, 0x33, 0xa2, 0xfc, 0x63, 0xbd, 0x54, 0xb3, 0x5d, 0x5d, 0xdc,
	0xa0, 0xe2, 0x06, 0x73, 0x6c, 0xae, 0x3b, 0x54, 0xdc, 0x74, 0xfd, 0x6e, 0x75, 0xf6, 0xc3, 0xec,
	0x75, 0xed, 0xaa, 0x18, 0x7a, 0x94, 0xeb, 0xcd, 0xd5, 0x95, 0xb7, 0xde, 0x08, 0xd7, 0x4b, 0xf9,
	0x0f, 0x5d, 0xe6, 0x34, 0x57, 0x57, 0x8c, 0x7c, 0x44, 0xdb, 0x0c, 0x18, 0xba, 0x0e, 0xf3, 0x16,
	0x1d, 0xc8, 0x00, 0x29, 0x19, 0xe0, 0xe2, 0x81, 0x02, 0xe4, 0x2e, 0xd2, 0x41, 0xc4, 0x9f, 0xb3,
	0xe8, 0xa0, 0x19, 0x30, 0xed, 0x5b, 0x58, 0xde, 0xa7, 0xde, 0xcb, 0x44, 0xd0, 0x9b, 0x64, 0x18,
	0x81, 0x93, 0x62, 0xaf, 0xc0, 0xf4, 0x76, 0x9d, 0xf5, 0x03, 0xa5, 0x91, 0x8e, 0x68, 0x23, 0x36,
	0xed, 0x37, 0x00, 0xf1, 0xd4, 0xc6, 0xda, 0x8c, 0x0b, 0x7f, 0x78, 0xd5, 0x15, 0xa4, 0xc7, 0xff,
	0xd3, 0xfb, 0xfb, 0x3b, 0x80, 0xc7, 0xf6, 0x4a, 0x1a, 0x69, 0x70, 0x81, 0x78, 0x5e, 0x8f, 0x99,
	0x24, 0xfa, 0x7b, 0xc4, 0xf9, 0x66, 0x8c, 0x99, 0x3b, 0xa4, 0xc2, 0xbc, 0xd9, 0x63, 0x34, 0xfa,
	0xb0, 0xa5, 0xe4, 0xf3, 0xc4, 0x44, 0x25, 0x38, 0x4f, 0x1d, 0xab, 0x65, 0xc9, 0x49, 0xe3, 0x72,
	0x5d, 0x33, 0x06, 0xa4, 0x93, 0xd9, 0xe3, 0xa8, 0x08, 0xe7, 0xec, 0xb8, 0x33, 0x5c, 0x6e, 0x6b,
	0xc6, 0xd8, 0xb2, 0xd1, 0x32, 0x3c, 0xe4, 0xfa, 0x36, 0x71, 0xd8, 0xad, 0x24, 0x76, 0x56, 0x02,
	0x66, 0x2f, 0xa3, 0x2f, 0x44, 0xc0, 0xa9, 0x1f, 0xfd, 0xca, 0xa2, 0xd7, 0xd8, 0x68, 0xfc, 0x02,
	0x1e, 0x8f, 0x30, 0x58, 0x1b, 0x61, 0xf0, 0x64, 0x84, 0x95, 0xa7, 0x23, 0xac, 0x6c, 0x8c, 0xb0,
	0xf2, 0x6c, 0x84, 0x95, 0xe7, 0x23, 0x0c, 0x6e, 0x87, 0x18, 0xdc, 0x09, 0xb1, 0x72, 0x3f, 0xc4,
	0xe0, 0x41, 0x88, 0x95, 0x87, 0x21, 0x56, 0x1e, 0x85, 0x58, 0x79, 0x1c, 0x62, 0xb0, 0x16, 0x62,
	0xf0, 0x24, 0xc4, 0xca, 0xd3, 0x10, 0x83, 0x8d, 0x10, 0x2b, 0xcf, 0x42, 0x0c, 0x9e, 0x87, 0x58,
	0xb9, 0x3d, 0xc6, 0xca, 0x9d, 0x31, 0x06, 0x77, 0xc7, 0x58, 0xb9, 0x37, 0xc6, 0xe0, 0xe7, 0x31,
	0x56, 0xee, 0x8f, 0xb1, 0xf2, 0x60, 0x8c, 0xc1, 0xc3, 0x31, 0x06, 0x8f, 0xc6, 0x18, 0x7c, 0x7a,
	0xfa, 0x9f, 0x8e, 0x8f, 0x60, 0x5e, 0xbb, 0x9d, 0x93, 0x9d, 0x39, 0xfb, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x06, 0x30, 0x83, 0xe2, 0x2d, 0x0a, 0x00, 0x00,
}

func (this *Tenant) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Tenant)
	if !ok {
		that2, ok := that.(Tenant)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.TenantIdentifiers.Equal(&that1.TenantIdentifiers) {
		return false
	}
	if !this.CreatedAt.Equal(that1.CreatedAt) {
		return false
	}
	if !this.UpdatedAt.Equal(that1.UpdatedAt) {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	if len(this.Attributes) != len(that1.Attributes) {
		return false
	}
	for i := range this.Attributes {
		if this.Attributes[i] != that1.Attributes[i] {
			return false
		}
	}
	if len(this.ContactInfo) != len(that1.ContactInfo) {
		return false
	}
	for i := range this.ContactInfo {
		if !this.ContactInfo[i].Equal(that1.ContactInfo[i]) {
			return false
		}
	}
	if this.State != that1.State {
		return false
	}
	if !this.Capabilities.Equal(&that1.Capabilities) {
		return false
	}
	return true
}
func (this *Tenants) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Tenants)
	if !ok {
		that2, ok := that.(Tenants)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Tenants) != len(that1.Tenants) {
		return false
	}
	for i := range this.Tenants {
		if !this.Tenants[i].Equal(that1.Tenants[i]) {
			return false
		}
	}
	return true
}
func (this *GetTenantRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetTenantRequest)
	if !ok {
		that2, ok := that.(GetTenantRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.TenantIdentifiers.Equal(&that1.TenantIdentifiers) {
		return false
	}
	if !this.FieldMask.Equal(&that1.FieldMask) {
		return false
	}
	return true
}
func (this *ListTenantsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListTenantsRequest)
	if !ok {
		that2, ok := that.(ListTenantsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.FieldMask.Equal(&that1.FieldMask) {
		return false
	}
	if this.Order != that1.Order {
		return false
	}
	if this.Limit != that1.Limit {
		return false
	}
	if this.Page != that1.Page {
		return false
	}
	return true
}
func (this *CreateTenantRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateTenantRequest)
	if !ok {
		that2, ok := that.(CreateTenantRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Tenant.Equal(&that1.Tenant) {
		return false
	}
	return true
}
func (this *UpdateTenantRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpdateTenantRequest)
	if !ok {
		that2, ok := that.(UpdateTenantRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Tenant.Equal(&that1.Tenant) {
		return false
	}
	if !this.FieldMask.Equal(&that1.FieldMask) {
		return false
	}
	return true
}
func (this *GetTenantIdentifiersForEndDeviceEUIsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetTenantIdentifiersForEndDeviceEUIsRequest)
	if !ok {
		that2, ok := that.(GetTenantIdentifiersForEndDeviceEUIsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.JoinEUI.Equal(that1.JoinEUI) {
		return false
	}
	if !this.DevEUI.Equal(that1.DevEUI) {
		return false
	}
	return true
}
func (this *GetTenantIdentifiersForGatewayEUIRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetTenantIdentifiersForGatewayEUIRequest)
	if !ok {
		that2, ok := that.(GetTenantIdentifiersForGatewayEUIRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.EUI.Equal(that1.EUI) {
		return false
	}
	return true
}
func (this *GetTenantRegistryTotalsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetTenantRegistryTotalsRequest)
	if !ok {
		that2, ok := that.(GetTenantRegistryTotalsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.TenantIdentifiers.Equal(&that1.TenantIdentifiers) {
		return false
	}
	if !this.FieldMask.Equal(&that1.FieldMask) {
		return false
	}
	return true
}
func (this *TenantRegistryTotals) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TenantRegistryTotals)
	if !ok {
		that2, ok := that.(TenantRegistryTotals)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Applications != that1.Applications {
		return false
	}
	if this.Clients != that1.Clients {
		return false
	}
	if this.EndDevices != that1.EndDevices {
		return false
	}
	if this.Gateways != that1.Gateways {
		return false
	}
	if this.Organizations != that1.Organizations {
		return false
	}
	if this.Users != that1.Users {
		return false
	}
	return true
}
func (m *Tenant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tenant) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.TenantIdentifiers.Size()))
	n1, err := m.TenantIdentifiers.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x12
	i++
	i = encodeVarintTenant(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(m.CreatedAt)))
	n2, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	dAtA[i] = 0x1a
	i++
	i = encodeVarintTenant(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(m.UpdatedAt)))
	n3, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.UpdatedAt, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	if len(m.Name) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintTenant(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Description) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintTenant(dAtA, i, uint64(len(m.Description)))
		i += copy(dAtA[i:], m.Description)
	}
	if len(m.Attributes) > 0 {
		for k := range m.Attributes {
			dAtA[i] = 0x32
			i++
			v := m.Attributes[k]
			mapSize := 1 + len(k) + sovTenant(uint64(len(k))) + 1 + len(v) + sovTenant(uint64(len(v)))
			i = encodeVarintTenant(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintTenant(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintTenant(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.ContactInfo) > 0 {
		for _, msg := range m.ContactInfo {
			dAtA[i] = 0x3a
			i++
			i = encodeVarintTenant(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.State != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintTenant(dAtA, i, uint64(m.State))
	}
	dAtA[i] = 0x4a
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.Capabilities.Size()))
	n4, err := m.Capabilities.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	return i, nil
}

func (m *Tenants) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tenants) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Tenants) > 0 {
		for _, msg := range m.Tenants {
			dAtA[i] = 0xa
			i++
			i = encodeVarintTenant(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *GetTenantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTenantRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.TenantIdentifiers.Size()))
	n5, err := m.TenantIdentifiers.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n5
	dAtA[i] = 0x12
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.FieldMask.Size()))
	n6, err := m.FieldMask.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n6
	return i, nil
}

func (m *ListTenantsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListTenantsRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.FieldMask.Size()))
	n7, err := m.FieldMask.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n7
	if len(m.Order) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTenant(dAtA, i, uint64(len(m.Order)))
		i += copy(dAtA[i:], m.Order)
	}
	if m.Limit != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintTenant(dAtA, i, uint64(m.Limit))
	}
	if m.Page != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintTenant(dAtA, i, uint64(m.Page))
	}
	return i, nil
}

func (m *CreateTenantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateTenantRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.Tenant.Size()))
	n8, err := m.Tenant.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n8
	return i, nil
}

func (m *UpdateTenantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateTenantRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.Tenant.Size()))
	n9, err := m.Tenant.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n9
	dAtA[i] = 0x12
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.FieldMask.Size()))
	n10, err := m.FieldMask.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n10
	return i, nil
}

func (m *GetTenantIdentifiersForEndDeviceEUIsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTenantIdentifiersForEndDeviceEUIsRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.JoinEUI.Size()))
	n11, err := m.JoinEUI.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n11
	dAtA[i] = 0x12
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.DevEUI.Size()))
	n12, err := m.DevEUI.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n12
	return i, nil
}

func (m *GetTenantIdentifiersForGatewayEUIRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTenantIdentifiersForGatewayEUIRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.EUI.Size()))
	n13, err := m.EUI.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n13
	return i, nil
}

func (m *GetTenantRegistryTotalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTenantRegistryTotalsRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.TenantIdentifiers.Size()))
	n14, err := m.TenantIdentifiers.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n14
	dAtA[i] = 0x12
	i++
	i = encodeVarintTenant(dAtA, i, uint64(m.FieldMask.Size()))
	n15, err := m.FieldMask.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n15
	return i, nil
}

func (m *TenantRegistryTotals) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TenantRegistryTotals) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Applications != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTenant(dAtA, i, m.Applications)
	}
	if m.Clients != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTenant(dAtA, i, m.Clients)
	}
	if m.EndDevices != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintTenant(dAtA, i, m.EndDevices)
	}
	if m.Gateways != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintTenant(dAtA, i, m.Gateways)
	}
	if m.Organizations != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintTenant(dAtA, i, m.Organizations)
	}
	if m.Users != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintTenant(dAtA, i, m.Users)
	}
	return i, nil
}

func encodeVarintTenant(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedTenant(r randyTenant, easy bool) *Tenant {
	this := &Tenant{}
	v1 := NewPopulatedTenantIdentifiers(r, easy)
	this.TenantIdentifiers = *v1
	v2 := github_com_gogo_protobuf_types.NewPopulatedStdTime(r, easy)
	this.CreatedAt = *v2
	v3 := github_com_gogo_protobuf_types.NewPopulatedStdTime(r, easy)
	this.UpdatedAt = *v3
	this.Name = randStringTenant(r)
	this.Description = randStringTenant(r)
	if r.Intn(10) != 0 {
		v4 := r.Intn(10)
		this.Attributes = make(map[string]string)
		for i := 0; i < v4; i++ {
			this.Attributes[randStringTenant(r)] = randStringTenant(r)
		}
	}
	if r.Intn(10) != 0 {
		v5 := r.Intn(5)
		this.ContactInfo = make([]*ttnpb.ContactInfo, v5)
		for i := 0; i < v5; i++ {
			this.ContactInfo[i] = ttnpb.NewPopulatedContactInfo(r, easy)
		}
	}
	this.State = ttnpb.State([]int32{0, 1, 2, 3, 4}[r.Intn(5)])
	v6 := types.NewPopulatedStruct(r, easy)
	this.Capabilities = *v6
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedTenants(r randyTenant, easy bool) *Tenants {
	this := &Tenants{}
	if r.Intn(10) != 0 {
		v7 := r.Intn(5)
		this.Tenants = make([]*Tenant, v7)
		for i := 0; i < v7; i++ {
			this.Tenants[i] = NewPopulatedTenant(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetTenantRequest(r randyTenant, easy bool) *GetTenantRequest {
	this := &GetTenantRequest{}
	v8 := NewPopulatedTenantIdentifiers(r, easy)
	this.TenantIdentifiers = *v8
	v9 := types.NewPopulatedFieldMask(r, easy)
	this.FieldMask = *v9
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedListTenantsRequest(r randyTenant, easy bool) *ListTenantsRequest {
	this := &ListTenantsRequest{}
	v10 := types.NewPopulatedFieldMask(r, easy)
	this.FieldMask = *v10
	this.Order = randStringTenant(r)
	this.Limit = r.Uint32()
	this.Page = r.Uint32()
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedCreateTenantRequest(r randyTenant, easy bool) *CreateTenantRequest {
	this := &CreateTenantRequest{}
	v11 := NewPopulatedTenant(r, easy)
	this.Tenant = *v11
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedUpdateTenantRequest(r randyTenant, easy bool) *UpdateTenantRequest {
	this := &UpdateTenantRequest{}
	v12 := NewPopulatedTenant(r, easy)
	this.Tenant = *v12
	v13 := types.NewPopulatedFieldMask(r, easy)
	this.FieldMask = *v13
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetTenantIdentifiersForEndDeviceEUIsRequest(r randyTenant, easy bool) *GetTenantIdentifiersForEndDeviceEUIsRequest {
	this := &GetTenantIdentifiersForEndDeviceEUIsRequest{}
	v14 := go_thethings_network_lorawan_stack_pkg_types.NewPopulatedEUI64(r)
	this.JoinEUI = *v14
	v15 := go_thethings_network_lorawan_stack_pkg_types.NewPopulatedEUI64(r)
	this.DevEUI = *v15
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetTenantIdentifiersForGatewayEUIRequest(r randyTenant, easy bool) *GetTenantIdentifiersForGatewayEUIRequest {
	this := &GetTenantIdentifiersForGatewayEUIRequest{}
	v16 := go_thethings_network_lorawan_stack_pkg_types.NewPopulatedEUI64(r)
	this.EUI = *v16
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetTenantRegistryTotalsRequest(r randyTenant, easy bool) *GetTenantRegistryTotalsRequest {
	this := &GetTenantRegistryTotalsRequest{}
	v17 := NewPopulatedTenantIdentifiers(r, easy)
	this.TenantIdentifiers = *v17
	v18 := types.NewPopulatedFieldMask(r, easy)
	this.FieldMask = *v18
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedTenantRegistryTotals(r randyTenant, easy bool) *TenantRegistryTotals {
	this := &TenantRegistryTotals{}
	this.Applications = uint64(r.Uint32())
	this.Clients = uint64(r.Uint32())
	this.EndDevices = uint64(r.Uint32())
	this.Gateways = uint64(r.Uint32())
	this.Organizations = uint64(r.Uint32())
	this.Users = uint64(r.Uint32())
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyTenant interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneTenant(r randyTenant) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringTenant(r randyTenant) string {
	v19 := r.Intn(100)
	tmps := make([]rune, v19)
	for i := 0; i < v19; i++ {
		tmps[i] = randUTF8RuneTenant(r)
	}
	return string(tmps)
}
func randUnrecognizedTenant(r randyTenant, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldTenant(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldTenant(dAtA []byte, r randyTenant, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateTenant(dAtA, uint64(key))
		v20 := r.Int63()
		if r.Intn(2) == 0 {
			v20 *= -1
		}
		dAtA = encodeVarintPopulateTenant(dAtA, uint64(v20))
	case 1:
		dAtA = encodeVarintPopulateTenant(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateTenant(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateTenant(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateTenant(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateTenant(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(v&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Tenant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TenantIdentifiers.Size()
	n += 1 + l + sovTenant(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovTenant(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.UpdatedAt)
	n += 1 + l + sovTenant(uint64(l))
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTenant(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTenant(uint64(l))
	}
	if len(m.Attributes) > 0 {
		for k, v := range m.Attributes {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovTenant(uint64(len(k))) + 1 + len(v) + sovTenant(uint64(len(v)))
			n += mapEntrySize + 1 + sovTenant(uint64(mapEntrySize))
		}
	}
	if len(m.ContactInfo) > 0 {
		for _, e := range m.ContactInfo {
			l = e.Size()
			n += 1 + l + sovTenant(uint64(l))
		}
	}
	if m.State != 0 {
		n += 1 + sovTenant(uint64(m.State))
	}
	l = m.Capabilities.Size()
	n += 1 + l + sovTenant(uint64(l))
	return n
}

func (m *Tenants) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Tenants) > 0 {
		for _, e := range m.Tenants {
			l = e.Size()
			n += 1 + l + sovTenant(uint64(l))
		}
	}
	return n
}

func (m *GetTenantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TenantIdentifiers.Size()
	n += 1 + l + sovTenant(uint64(l))
	l = m.FieldMask.Size()
	n += 1 + l + sovTenant(uint64(l))
	return n
}

func (m *ListTenantsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FieldMask.Size()
	n += 1 + l + sovTenant(uint64(l))
	l = len(m.Order)
	if l > 0 {
		n += 1 + l + sovTenant(uint64(l))
	}
	if m.Limit != 0 {
		n += 1 + sovTenant(uint64(m.Limit))
	}
	if m.Page != 0 {
		n += 1 + sovTenant(uint64(m.Page))
	}
	return n
}

func (m *CreateTenantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Tenant.Size()
	n += 1 + l + sovTenant(uint64(l))
	return n
}

func (m *UpdateTenantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Tenant.Size()
	n += 1 + l + sovTenant(uint64(l))
	l = m.FieldMask.Size()
	n += 1 + l + sovTenant(uint64(l))
	return n
}

func (m *GetTenantIdentifiersForEndDeviceEUIsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.JoinEUI.Size()
	n += 1 + l + sovTenant(uint64(l))
	l = m.DevEUI.Size()
	n += 1 + l + sovTenant(uint64(l))
	return n
}

func (m *GetTenantIdentifiersForGatewayEUIRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.EUI.Size()
	n += 1 + l + sovTenant(uint64(l))
	return n
}

func (m *GetTenantRegistryTotalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TenantIdentifiers.Size()
	n += 1 + l + sovTenant(uint64(l))
	l = m.FieldMask.Size()
	n += 1 + l + sovTenant(uint64(l))
	return n
}

func (m *TenantRegistryTotals) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Applications != 0 {
		n += 1 + sovTenant(m.Applications)
	}
	if m.Clients != 0 {
		n += 1 + sovTenant(m.Clients)
	}
	if m.EndDevices != 0 {
		n += 1 + sovTenant(m.EndDevices)
	}
	if m.Gateways != 0 {
		n += 1 + sovTenant(m.Gateways)
	}
	if m.Organizations != 0 {
		n += 1 + sovTenant(m.Organizations)
	}
	if m.Users != 0 {
		n += 1 + sovTenant(m.Users)
	}
	return n
}

func sovTenant(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTenant(x uint64) (n int) {
	return sovTenant((x << 1) ^ uint64((int64(x) >> 63)))
}
func (this *Tenant) String() string {
	if this == nil {
		return "nil"
	}
	keysForAttributes := make([]string, 0, len(this.Attributes))
	for k := range this.Attributes {
		keysForAttributes = append(keysForAttributes, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAttributes)
	mapStringForAttributes := "map[string]string{"
	for _, k := range keysForAttributes {
		mapStringForAttributes += fmt.Sprintf("%v: %v,", k, this.Attributes[k])
	}
	mapStringForAttributes += "}"
	s := strings.Join([]string{`&Tenant{`,
		`TenantIdentifiers:` + strings.Replace(strings.Replace(this.TenantIdentifiers.String(), "TenantIdentifiers", "TenantIdentifiers", 1), `&`, ``, 1) + `,`,
		`CreatedAt:` + strings.Replace(strings.Replace(this.CreatedAt.String(), "Timestamp", "types.Timestamp", 1), `&`, ``, 1) + `,`,
		`UpdatedAt:` + strings.Replace(strings.Replace(this.UpdatedAt.String(), "Timestamp", "types.Timestamp", 1), `&`, ``, 1) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`Attributes:` + mapStringForAttributes + `,`,
		`ContactInfo:` + strings.Replace(fmt.Sprintf("%v", this.ContactInfo), "ContactInfo", "ttnpb.ContactInfo", 1) + `,`,
		`State:` + fmt.Sprintf("%v", this.State) + `,`,
		`Capabilities:` + strings.Replace(strings.Replace(this.Capabilities.String(), "Struct", "types.Struct", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Tenants) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Tenants{`,
		`Tenants:` + strings.Replace(fmt.Sprintf("%v", this.Tenants), "Tenant", "Tenant", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetTenantRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetTenantRequest{`,
		`TenantIdentifiers:` + strings.Replace(strings.Replace(this.TenantIdentifiers.String(), "TenantIdentifiers", "TenantIdentifiers", 1), `&`, ``, 1) + `,`,
		`FieldMask:` + strings.Replace(strings.Replace(this.FieldMask.String(), "FieldMask", "types.FieldMask", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListTenantsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListTenantsRequest{`,
		`FieldMask:` + strings.Replace(strings.Replace(this.FieldMask.String(), "FieldMask", "types.FieldMask", 1), `&`, ``, 1) + `,`,
		`Order:` + fmt.Sprintf("%v", this.Order) + `,`,
		`Limit:` + fmt.Sprintf("%v", this.Limit) + `,`,
		`Page:` + fmt.Sprintf("%v", this.Page) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateTenantRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateTenantRequest{`,
		`Tenant:` + strings.Replace(strings.Replace(this.Tenant.String(), "Tenant", "Tenant", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateTenantRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateTenantRequest{`,
		`Tenant:` + strings.Replace(strings.Replace(this.Tenant.String(), "Tenant", "Tenant", 1), `&`, ``, 1) + `,`,
		`FieldMask:` + strings.Replace(strings.Replace(this.FieldMask.String(), "FieldMask", "types.FieldMask", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetTenantIdentifiersForEndDeviceEUIsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetTenantIdentifiersForEndDeviceEUIsRequest{`,
		`JoinEUI:` + fmt.Sprintf("%v", this.JoinEUI) + `,`,
		`DevEUI:` + fmt.Sprintf("%v", this.DevEUI) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetTenantIdentifiersForGatewayEUIRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetTenantIdentifiersForGatewayEUIRequest{`,
		`EUI:` + fmt.Sprintf("%v", this.EUI) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetTenantRegistryTotalsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetTenantRegistryTotalsRequest{`,
		`TenantIdentifiers:` + strings.Replace(strings.Replace(this.TenantIdentifiers.String(), "TenantIdentifiers", "TenantIdentifiers", 1), `&`, ``, 1) + `,`,
		`FieldMask:` + strings.Replace(strings.Replace(this.FieldMask.String(), "FieldMask", "types.FieldMask", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TenantRegistryTotals) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TenantRegistryTotals{`,
		`Applications:` + fmt.Sprintf("%v", this.Applications) + `,`,
		`Clients:` + fmt.Sprintf("%v", this.Clients) + `,`,
		`EndDevices:` + fmt.Sprintf("%v", this.EndDevices) + `,`,
		`Gateways:` + fmt.Sprintf("%v", this.Gateways) + `,`,
		`Organizations:` + fmt.Sprintf("%v", this.Organizations) + `,`,
		`Users:` + fmt.Sprintf("%v", this.Users) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTenant(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Tenant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tenant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tenant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantIdentifiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TenantIdentifiers.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Attributes == nil {
				m.Attributes = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTenant
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTenant
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTenant
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthTenant
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTenant
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthTenant
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthTenant
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTenant(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthTenant
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Attributes[mapkey] = mapvalue
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContactInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContactInfo = append(m.ContactInfo, &ttnpb.ContactInfo{})
			if err := m.ContactInfo[len(m.ContactInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= ttnpb.State(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capabilities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Capabilities.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTenant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tenants) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tenants: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tenants: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenants", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenants = append(m.Tenants, &Tenant{})
			if err := m.Tenants[len(m.Tenants)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTenant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTenantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTenantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTenantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantIdentifiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TenantIdentifiers.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldMask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FieldMask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTenant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListTenantsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListTenantsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListTenantsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldMask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FieldMask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Order = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTenant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateTenantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateTenantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateTenantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tenant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTenant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateTenantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateTenantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateTenantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tenant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldMask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FieldMask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTenant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTenantIdentifiersForEndDeviceEUIsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTenantIdentifiersForEndDeviceEUIsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTenantIdentifiersForEndDeviceEUIsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinEUI", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.JoinEUI.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DevEUI", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DevEUI.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTenant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTenantIdentifiersForGatewayEUIRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTenantIdentifiersForGatewayEUIRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTenantIdentifiersForGatewayEUIRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EUI", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EUI.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTenant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTenantRegistryTotalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTenantRegistryTotalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTenantRegistryTotalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantIdentifiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TenantIdentifiers.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldMask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTenant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTenant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FieldMask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTenant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TenantRegistryTotals) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TenantRegistryTotals: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TenantRegistryTotals: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Applications", wireType)
			}
			m.Applications = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Applications |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Clients", wireType)
			}
			m.Clients = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Clients |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndDevices", wireType)
			}
			m.EndDevices = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndDevices |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gateways", wireType)
			}
			m.Gateways = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Gateways |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Organizations", wireType)
			}
			m.Organizations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Organizations |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Users", wireType)
			}
			m.Users = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Users |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTenant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTenant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTenant(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTenant
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTenant
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTenant
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthTenant
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTenant
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTenant(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthTenant
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTenant = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTenant   = fmt.Errorf("proto: integer overflow")
)
