// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorawan-stack/api/tti/tenant_services.proto

package ttipb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("lorawan-stack/api/tti/tenant_services.proto", fileDescriptor_f411f114fe8fe8a6)
}
func init() {
	golang_proto.RegisterFile("lorawan-stack/api/tti/tenant_services.proto", fileDescriptor_f411f114fe8fe8a6)
}

var fileDescriptor_f411f114fe8fe8a6 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x3d, 0x4c, 0x14, 0x41,
	0x14, 0x9e, 0x51, 0x73, 0x9a, 0x4d, 0x24, 0x3a, 0x1a, 0x4c, 0x0e, 0xf2, 0x94, 0x95, 0x84, 0x04,
	0xc3, 0x6c, 0x94, 0x42, 0xa3, 0x9d, 0x72, 0x5e, 0x48, 0xac, 0x0c, 0xd7, 0xd0, 0x98, 0x81, 0x1b,
	0x96, 0x09, 0xe7, 0xee, 0xb2, 0xf3, 0xe0, 0x72, 0x1a, 0x92, 0x8b, 0x15, 0xa5, 0x89, 0x8d, 0xa5,
	0x31, 0x31, 0x52, 0x52, 0x52, 0x52, 0x52, 0x92, 0xd8, 0x50, 0xb2, 0xb3, 0x16, 0x94, 0x94, 0x94,
	0xe6, 0xf6, 0xe7, 0xe0, 0x8e, 0xf5, 0xb8, 0xee, 0xee, 0xcd, 0xfb, 0x7e, 0xe6, 0x7b, 0x6f, 0xc7,
	0x7a, 0xd2, 0xf0, 0x43, 0xd1, 0x14, 0xde, 0x8c, 0x46, 0xb1, 0xbc, 0xe6, 0x88, 0x40, 0x39, 0x88,
	0xca, 0x41, 0xe9, 0x09, 0x0f, 0x3f, 0x68, 0x19, 0x6e, 0xaa, 0x65, 0xa9, 0x79, 0x10, 0xfa, 0xe8,
	0xb3, 0x11, 0x44, 0xc5, 0x33, 0x00, 0xdf, 0x9c, 0x2d, 0x8f, 0xbb, 0xbe, 0xef, 0x36, 0x64, 0x82,
	0x12, 0x9e, 0xe7, 0xa3, 0x40, 0xe5, 0x7b, 0x59, 0x77, 0x79, 0x2c, 0x3b, 0x4d, 0xfe, 0x2d, 0x6d,
	0xac, 0x38, 0xf2, 0x63, 0x80, 0xad, 0xec, 0x70, 0xaa, 0x58, 0x57, 0xd5, 0xa5, 0x87, 0x6a, 0x45,
	0xc9, 0x30, 0x67, 0xb1, 0x07, 0x19, 0x4c, 0x7b, 0x9e, 0xfd, 0xbe, 0x69, 0x8d, 0x2c, 0x24, 0x85,
	0xf7, 0xd2, 0x55, 0x1a, 0xc3, 0x16, 0x5b, 0xb4, 0x4a, 0x6f, 0x42, 0x29, 0x50, 0xb2, 0xc7, 0xbc,
	0xd7, 0x35, 0x4f, 0xeb, 0x79, 0xff, 0xfa, 0x86, 0xd4, 0x58, 0x1e, 0xed, 0x6f, 0x4a, 0x8f, 0xed,
	0x7b, 0x5f, 0xfe, 0xfc, 0xfd, 0x76, 0xed, 0xb6, 0x7d, 0x2b, 0x13, 0xd4, 0x2f, 0xe9, 0x34, 0x5b,
	0xb5, 0xae, 0x57, 0x25, 0xb2, 0x47, 0xfd, 0x98, 0xaa, 0xc4, 0xe1, 0x58, 0xa7, 0x12, 0xd6, 0x09,
	0xf6, 0x30, 0x67, 0x75, 0x3e, 0x67, 0x81, 0xab, 0xba, 0xe6, 0xdd, 0x9f, 0x5b, 0xec, 0x27, 0xb5,
	0xee, 0x56, 0x65, 0xf7, 0x56, 0x0b, 0x3e, 0x8a, 0x86, 0x66, 0x7c, 0x80, 0xf0, 0xc5, 0xc6, 0xdc,
	0xc6, 0x64, 0xb1, 0x8d, 0xde, 0x66, 0xfb, 0x79, 0x62, 0xea, 0x29, 0x73, 0xae, 0x30, 0xe5, 0x84,
	0x19, 0x6e, 0x06, 0x53, 0x3b, 0x35, 0xeb, 0xc6, 0x3b, 0xa5, 0x91, 0xd9, 0xfd, 0x32, 0x9d, 0x6a,
	0x2a, 0xd5, 0xb5, 0xf2, 0xa0, 0xd8, 0x8a, 0xb6, 0xef, 0x24, 0xea, 0x16, 0xeb, 0x06, 0xcd, 0xd6,
	0xad, 0x52, 0x2d, 0xa8, 0x17, 0x4e, 0x30, 0xad, 0x0f, 0x97, 0xf5, 0x74, 0x42, 0x3c, 0x59, 0xbe,
	0x94, 0x35, 0xef, 0xbd, 0x56, 0x67, 0xb0, 0xc2, 0x2a, 0xcd, 0xc9, 0x86, 0x44, 0xc9, 0x26, 0x8a,
	0xd9, 0xe6, 0xcf, 0xd7, 0xb3, 0x3c, 0xca, 0xd3, 0xfd, 0xe6, 0xf9, 0x7e, 0xf3, 0x4a, 0x67, 0xbf,
	0xed, 0xf1, 0x44, 0x70, 0x74, 0xfa, 0x7e, 0x41, 0x8e, 0x5b, 0xac, 0x4d, 0x2d, 0xa8, 0xca, 0x8b,
	0x44, 0x6f, 0xfd, 0xb0, 0xe2, 0xd5, 0xe7, 0x64, 0xe7, 0x43, 0xab, 0xd4, 0xe6, 0x35, 0x7b, 0xf5,
	0xdf, 0xf1, 0x0e, 0x40, 0xe5, 0x31, 0x5c, 0x6d, 0x9c, 0x7d, 0xb2, 0xc6, 0x2e, 0x39, 0xa8, 0x0a,
	0x94, 0x4d, 0xd1, 0xaa, 0xd4, 0xe6, 0xd9, 0x8b, 0x21, 0xe5, 0xcf, 0x21, 0xc3, 0x6b, 0xbf, 0xfe,
	0x45, 0x0f, 0x22, 0xa0, 0x87, 0x11, 0xd0, 0xa3, 0x08, 0xc8, 0x71, 0x04, 0xe4, 0x24, 0x02, 0x72,
	0x1a, 0x01, 0x39, 0x8b, 0x80, 0xb6, 0x0d, 0xd0, 0x6d, 0x03, 0x64, 0xc7, 0x00, 0xdd, 0x35, 0x40,
	0xf6, 0x0c, 0x90, 0x7d, 0x03, 0xe4, 0xc0, 0x00, 0x3d, 0x34, 0x40, 0x8f, 0x0c, 0x90, 0x63, 0x03,
	0xf4, 0xc4, 0x00, 0x39, 0x35, 0x40, 0xcf, 0x0c, 0x90, 0x76, 0x0c, 0x64, 0x3b, 0x06, 0xfa, 0x35,
	0x06, 0xf2, 0x3d, 0x06, 0xfa, 0x23, 0x06, 0xb2, 0x13, 0x03, 0xd9, 0x8d, 0x81, 0xee, 0xc5, 0x40,
	0xf7, 0x63, 0xa0, 0x8b, 0x8e, 0xeb, 0x73, 0x5c, 0x95, 0xb8, 0xaa, 0x3c, 0x57, 0x73, 0x4f, 0x62,
	0xd3, 0x0f, 0xd7, 0x9c, 0xde, 0x97, 0x65, 0x73, 0xd6, 0x09, 0xd6, 0xdc, 0xce, 0xe3, 0x12, 0x2c,
	0x2d, 0x95, 0x92, 0xa1, 0xce, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x69, 0xcf, 0xbd, 0xcb, 0x1f,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TenantRegistryClient is the client API for TenantRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TenantRegistryClient interface {
	Create(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	Get(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	GetRegistryTotals(ctx context.Context, in *GetTenantRegistryTotalsRequest, opts ...grpc.CallOption) (*TenantRegistryTotals, error)
	List(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*Tenants, error)
	Update(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	Delete(ctx context.Context, in *TenantIdentifiers, opts ...grpc.CallOption) (*types.Empty, error)
	GetIdentifiersForEndDeviceEUIs(ctx context.Context, in *GetTenantIdentifiersForEndDeviceEUIsRequest, opts ...grpc.CallOption) (*TenantIdentifiers, error)
	GetIdentifiersForGatewayEUI(ctx context.Context, in *GetTenantIdentifiersForGatewayEUIRequest, opts ...grpc.CallOption) (*TenantIdentifiers, error)
}

type tenantRegistryClient struct {
	cc *grpc.ClientConn
}

func NewTenantRegistryClient(cc *grpc.ClientConn) TenantRegistryClient {
	return &tenantRegistryClient{cc}
}

func (c *tenantRegistryClient) Create(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, "/tti.lorawan.v3.TenantRegistry/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantRegistryClient) Get(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, "/tti.lorawan.v3.TenantRegistry/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantRegistryClient) GetRegistryTotals(ctx context.Context, in *GetTenantRegistryTotalsRequest, opts ...grpc.CallOption) (*TenantRegistryTotals, error) {
	out := new(TenantRegistryTotals)
	err := c.cc.Invoke(ctx, "/tti.lorawan.v3.TenantRegistry/GetRegistryTotals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantRegistryClient) List(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*Tenants, error) {
	out := new(Tenants)
	err := c.cc.Invoke(ctx, "/tti.lorawan.v3.TenantRegistry/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantRegistryClient) Update(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, "/tti.lorawan.v3.TenantRegistry/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantRegistryClient) Delete(ctx context.Context, in *TenantIdentifiers, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/tti.lorawan.v3.TenantRegistry/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantRegistryClient) GetIdentifiersForEndDeviceEUIs(ctx context.Context, in *GetTenantIdentifiersForEndDeviceEUIsRequest, opts ...grpc.CallOption) (*TenantIdentifiers, error) {
	out := new(TenantIdentifiers)
	err := c.cc.Invoke(ctx, "/tti.lorawan.v3.TenantRegistry/GetIdentifiersForEndDeviceEUIs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantRegistryClient) GetIdentifiersForGatewayEUI(ctx context.Context, in *GetTenantIdentifiersForGatewayEUIRequest, opts ...grpc.CallOption) (*TenantIdentifiers, error) {
	out := new(TenantIdentifiers)
	err := c.cc.Invoke(ctx, "/tti.lorawan.v3.TenantRegistry/GetIdentifiersForGatewayEUI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantRegistryServer is the server API for TenantRegistry service.
type TenantRegistryServer interface {
	Create(context.Context, *CreateTenantRequest) (*Tenant, error)
	Get(context.Context, *GetTenantRequest) (*Tenant, error)
	GetRegistryTotals(context.Context, *GetTenantRegistryTotalsRequest) (*TenantRegistryTotals, error)
	List(context.Context, *ListTenantsRequest) (*Tenants, error)
	Update(context.Context, *UpdateTenantRequest) (*Tenant, error)
	Delete(context.Context, *TenantIdentifiers) (*types.Empty, error)
	GetIdentifiersForEndDeviceEUIs(context.Context, *GetTenantIdentifiersForEndDeviceEUIsRequest) (*TenantIdentifiers, error)
	GetIdentifiersForGatewayEUI(context.Context, *GetTenantIdentifiersForGatewayEUIRequest) (*TenantIdentifiers, error)
}

// UnimplementedTenantRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedTenantRegistryServer struct {
}

func (*UnimplementedTenantRegistryServer) Create(ctx context.Context, req *CreateTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedTenantRegistryServer) Get(ctx context.Context, req *GetTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedTenantRegistryServer) GetRegistryTotals(ctx context.Context, req *GetTenantRegistryTotalsRequest) (*TenantRegistryTotals, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegistryTotals not implemented")
}
func (*UnimplementedTenantRegistryServer) List(ctx context.Context, req *ListTenantsRequest) (*Tenants, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedTenantRegistryServer) Update(ctx context.Context, req *UpdateTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedTenantRegistryServer) Delete(ctx context.Context, req *TenantIdentifiers) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedTenantRegistryServer) GetIdentifiersForEndDeviceEUIs(ctx context.Context, req *GetTenantIdentifiersForEndDeviceEUIsRequest) (*TenantIdentifiers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentifiersForEndDeviceEUIs not implemented")
}
func (*UnimplementedTenantRegistryServer) GetIdentifiersForGatewayEUI(ctx context.Context, req *GetTenantIdentifiersForGatewayEUIRequest) (*TenantIdentifiers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentifiersForGatewayEUI not implemented")
}

func RegisterTenantRegistryServer(s *grpc.Server, srv TenantRegistryServer) {
	s.RegisterService(&_TenantRegistry_serviceDesc, srv)
}

func _TenantRegistry_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantRegistryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tti.lorawan.v3.TenantRegistry/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantRegistryServer).Create(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantRegistry_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantRegistryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tti.lorawan.v3.TenantRegistry/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantRegistryServer).Get(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantRegistry_GetRegistryTotals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRegistryTotalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantRegistryServer).GetRegistryTotals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tti.lorawan.v3.TenantRegistry/GetRegistryTotals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantRegistryServer).GetRegistryTotals(ctx, req.(*GetTenantRegistryTotalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantRegistry_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantRegistryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tti.lorawan.v3.TenantRegistry/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantRegistryServer).List(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantRegistry_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantRegistryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tti.lorawan.v3.TenantRegistry/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantRegistryServer).Update(ctx, req.(*UpdateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantRegistry_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantIdentifiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantRegistryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tti.lorawan.v3.TenantRegistry/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantRegistryServer).Delete(ctx, req.(*TenantIdentifiers))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantRegistry_GetIdentifiersForEndDeviceEUIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantIdentifiersForEndDeviceEUIsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantRegistryServer).GetIdentifiersForEndDeviceEUIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tti.lorawan.v3.TenantRegistry/GetIdentifiersForEndDeviceEUIs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantRegistryServer).GetIdentifiersForEndDeviceEUIs(ctx, req.(*GetTenantIdentifiersForEndDeviceEUIsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantRegistry_GetIdentifiersForGatewayEUI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantIdentifiersForGatewayEUIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantRegistryServer).GetIdentifiersForGatewayEUI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tti.lorawan.v3.TenantRegistry/GetIdentifiersForGatewayEUI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantRegistryServer).GetIdentifiersForGatewayEUI(ctx, req.(*GetTenantIdentifiersForGatewayEUIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TenantRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tti.lorawan.v3.TenantRegistry",
	HandlerType: (*TenantRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TenantRegistry_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TenantRegistry_Get_Handler,
		},
		{
			MethodName: "GetRegistryTotals",
			Handler:    _TenantRegistry_GetRegistryTotals_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TenantRegistry_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TenantRegistry_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TenantRegistry_Delete_Handler,
		},
		{
			MethodName: "GetIdentifiersForEndDeviceEUIs",
			Handler:    _TenantRegistry_GetIdentifiersForEndDeviceEUIs_Handler,
		},
		{
			MethodName: "GetIdentifiersForGatewayEUI",
			Handler:    _TenantRegistry_GetIdentifiersForGatewayEUI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lorawan-stack/api/tti/tenant_services.proto",
}
